name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NVCC_FLAGS: "-allow-unsupported-compiler"
  TORCH_CUDA_ARCH_LIST: "7.0;7.5;8.0"
  DISTUTILS_USE_SDK: 1
  FORCE_CUDA: 1

jobs:
  build:
    runs-on: ${{ matrix.os-version }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os-version: ubuntu-latest
            python-version: '3.8'
            cuda-version: '11.3.1'
            torch-install-command: 'torch==1.11.0+cu113 torchvision==0.12.0+cu113 --extra-index-url https://download.pytorch.org/whl/cu113'

    steps:
      - uses: actions/setup-python@v4
        id: python
        with:
          python-version: ${{ matrix.python-version }}
      - id: prepare-build
        run: |
          git clone https://github.com/facebookresearch/xformers.git
          cd xformers
          git reset --hard 6c003f1f6e8dbe1dfa95158b6c9c371849fb8109
          git submodule update --init --recursive
          pip install ${{ matrix.torch-install-command }}
          pip install -r requirements.txt
          pip install wheel
      - uses: Jimver/cuda-toolkit@v0.2.8
        id: cuda-toolkit
        with:
          cuda: ${{ matrix.cuda-version }}
      - id: build
        env:
          CUDA_HOME: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}
        run: |
          cd xformers
          python setup.py bdist_wheel
      - uses: actions/upload-artifact@v3
        with:
          name: xformers-wheel-${{ matrix.os-version }}-${{ matrix.python-version }}-${{ matrix.cuda-version }}
          path: xformers/dist/*.whl
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - id: get-artifact
        uses: actions/download-artifact@v3
      - id: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*/*.whl"
          tag: ${{ github.run_id }}
          commit: ${{ github.sha }}